### PR TITLE
It's now possible to select the repos and issues

### PR DESCRIPTION
**Pull request by fdiogo**
I added the inquirer package which really eases the process of reading input from the user. Hope you guys like it.

It's now possible to select the repositories you're interested in and then select from the combined issues of those repositories. Now it always tries to create a label and use that newly created label.

For future changes, I'll create actual models we can use so we can easily control these edge cases.

### CODE REVIEW

**Comment by rajikaimal** [comment]
Great work ! Nice to see inquirer added to the package. Hope you did a functional test with this PR.

**Comment by rajikaimal** [comment]
Did a functional test, work fine. However I found few issues.
- if the user doesn't select any repository map function won't work. Exception should be handled.
- if a label already exists it gives out the whole error json. It would be great if only the error is shown.

Hope you can work on these issues with another PR.
Thanks.

**Comment by fdiogo** [comment]
Thanks for the quick reply. I did notice the json error but not the map issue. Will work on it. Thanks a lot for the feedback!

**Comment by rajikaimal** [comment]
Great !

**Pull request merged**
